### ISSUE TITLE
change in soundtechnique.md invisible

### ISSUE THREAD

**Issue by ofpetro** [simonyiszk/tanfolyam-web#6]
A soundtechnique.md fájlt módosítottam, hogy az AC stúdiós workshopja frissüljön, és merge-elve is van, de a honlapon nem látszik. Miért?

**Comment by kripod** [comment]
Valószínűleg azóta még nem lett újra deployolva az oldal @Freyb által.

**Comment by Freyb** [comment]
Deployolva
